.TH "mpl_copy" "3" "27 ноября 2012" "Linux" "MPL Functions Manual"
.
.SH ИМЯ
mpl_copy \-
скопировать mpl_int
.
.SH СИНТАКСИС
.nf
.B #include <mpl.h>
.sp
.BI "int mpl_copy(mpl_int *" dst ", const mpl_int *" src );
.fi
.
.SH ОПИСАНИЕ
Функция \fBmpl_copy\fP копирует содержимое переменной \fIsrc\fP
в переменную \fIdst\fP.
.
.SH "ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ"
Функция возвращает \fBMPL_OK\fP в случае успеха,
либо \fBMPL_NOMEM\fP в случае ошибки.
.
.SH "СМОТРИ ТАКЖЕ"
.BR mpl_swap (3),
.BR mpl_add (3),
.BR mpl_sub (3),
.BR mpl_div (3),
.BR mpl_mul (3),
