.TH "mpl_dbg" "3" "27 ноября 2012" "Linux" "MPL Functions Manual"
.
.SH ИМЯ
mpl_dbg \-
вывести отладочную информацию
.
.SH СИНТАКСИС
.nf
.B #include <mpl.h>
.sp
.BI "void mpl_dbg(const mpl_int *" a ", FILE *" fp );
.fi
.
.SH ОПИСАНИЕ
Функция \fBmpl_dbg\fP записывает в файл \fIfp\fP
следующиую отладочную информацию о переменной \fIa\fP:
указатель на переменную \fIa\fP,
номер вершины в числе,
знак числа,
указатель на массив с собственно числом,
а так же содержание этого массива.
.
.SH "СМОТРИ ТАКЖЕ"
.BR mpl_clear (3),
.BR mpl_clearv (3)
